version: "3"
volumes:
  pgdata:
services:
  ctu-web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ctu-main:/ctu-main

  ctu-db:
    image: postgres:12.2   #replace this with the required registry
    environment:
      POSTGRES_USER: ctu-sa
      POSTGRES_DB: ctu-db
      POSTGRES_PASS: devsecops
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

