version: "3"

services:
  ctu-web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ctu-main:/ctu-main
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"