apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "ctukubecluster"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "ctukubecluster"
    spec:
      containers:
        - name: "ctukubecluster"
          image: "stagingctu.azurecr.io/ctukubecluster"
          ports:
          - containerPort: 80